name: expression workflow

on:
  workflow_dispatch:
    inputs:
      isPass:
        description: Should it pass?
        type: choice
        default: 'yes'
        options:
          - 'yes'
          - 'no'
env:
  TEST_ENV: ${{ inputs.isPass == 'yes' }}

jobs:
  yes-job:
    if: inputs.isPass == 'yes'
    runs-on: ubuntu-latest
    steps:
      - name: print input when yes
        run: echo "The value is ${{ inputs.isPass }}"
        
      - name: printe nv from bash
        run: echo "TEST ENV is $TEST_ENV"
  
      - name: print env
        run: echo "The value is ${{ env.TEST_ENV }}"

  no-job:
    if: inputs.isPass == 'no'
    runs-on: ubuntu-latest
    steps:
      - name: print input when no
        run: echo "The value is ${{ inputs.isPass }}"
        
