name: expression workflow

on:
  workflow_dispatch:
    inputs:
      isPass:
        description: Should it pass?
        type: choice
        default: 'no'
        options:
          - 'yes'
          - 'no'
        
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: print input
        run: echo "The value is ${{ inputs.isPass }}"
  
