name: expression workflow

on:
  workflow_dispatch:
    inputs:
      isPass:
        description: Should it pass?
        type: choice
        default: 'yes'
        options:
          - 'yes'
          - 'no'
env:
  IS_PASS_ENV: ${{ inputs.isPass == 'yes' }}

jobs:
  yes-job:
    if: inputs.isPass == 'yes'
    runs-on: ubuntu-latest
    steps:
      - name: print input when yes
        run: echo "The value is ${{ inputs.isPass }}"
        
      - name: printe env from bash
        run: echo "TEST ENV is $IS_PASS_ENV"
  
      - name: print env
        run: echo "The value is ${{ env.IS_PASS_ENV }}"
        


  no-job:
    if: inputs.isPass == 'no'
    runs-on: ubuntu-latest
    steps:
      - name: print input when no
        run: echo "The value is ${{ inputs.isPass }}" 
        
      - name: fail job if no is the input 
        run: |
          echo "This fails the job. urrent input is ${{ inputs.isPass }}
          if [[ $IS_PASS_ENV == true ]]
          then
            exit 1
          fi
      - name: run when job fails
        if: failure()
        run: echo "The job has now failed"

    
