name: expression workflow

on:
  workflow_dispatch:
    input:
      isPass:
        description: Should it pass?
        type: boolean
        default: 'No'

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: print input
        run: echo "The value is ${{ github.event.input.isPass }}"
  
