name: expression workflow

on:
  workflow_dispatch:
    inputs:
      isPass:
        description: Should it pass?
        type: choice
        default: 'yes'
        options:
          - 'yes'
          - 'no'
        
jobs:
  yes-job:
    if: inputs.isPass == 'yes'
    runs-on: ubuntu-latest
    steps:
      - name: print input when yes
        run: echo "The value is ${{ inputs.isPass }}"

  no-job:
    if: inputs.isPass == 'no'
    runs-on: ubuntu-latest
    steps:
      - name: print input when no
        run: echo "The value is ${{ inputs.isPass }}"
        
