name: expression workflow

on:
  workflow_dispatch:
    inputs:
      isPass:
        description: Should it pass?
        type: choice
        default: 'yes'
        options:
          - 'yes'
          - 'no'
        
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: print input when yes
        if: inputs.isPass == 'yes'
        run: echo "The value is ${{ inputs.isPass }}"
        
      - name: print input when no
        if: inputs.isPass == 'no'
        run: echo "The value is ${{ inputs.isPass }}"
