name: hello actions

on:  
  repository_dispatch:
    types: [run_workflow]

  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "warning"
        type: choice
        options:
          - info
          - warning
          - debug
      tags:
        description: "Test scenario tags"
        required: false
        type: boolean
        
jobs:
  log-ext-inputs:
    runs-on: ubuntu-latest
    run: |
      echo "The payload is ${{ github.event.client_payload.mydata }}"


  log-the-inputs:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Log level: $LEVEL"
          echo "Tags: $TAGS"
        env:
          LEVEL: ${{ inputs.logLevel }}
          TAGS: ${{ inputs.tags }}
