name: running scripts

on:
  push:
    branches: main
  workflow_dispatch:
  
jobs:
  run-js:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v5 
        id: create-comment
        with:
          script: |
            console.log("This working?")
            
            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: "This is a comment"
              body: "I made this using gh actions"
            )};
            
            return "Dummy return to check the output of this step"
            
      - name: Get output from previous step
        run: echo "${{ steps.create-comment-outputs.result }}"
          
