name: running scripts

on:
  push:
    branches: main
  workflow_dispatch:
  
jobs:
  run-js:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v5 
        id: create comment
        with:
          script: |
            console.log("This working?")
          
